### ISSUE TITLE
Scaling on windows 11 doesnt work

### ISSUE THREAD

**Issue by Toylerrr** [Sneezedip/Steam-UI-Clone#2]
When using on windows 11 the window does scale correctly. Using 175% scaling makes the main tabs unusable. 

Other then that looks great! 
![image](https://github.com/Sneezedip/Steam-UI-Clone/assets/4400902/5462dea8-70bc-4d7b-b14d-b6ddb30c986e)

**Comment by Sneezedip** [comment]
Didn't know about that, i will update it . Thanks !!

**Comment by Sneezedip** [comment]
Now that im watching it, i think its because i used place() instead of grid(), and it may have changed because of the OS, im fixing it temporarily by changing the value for each OS, but later ill launch a new version with all .place() replaced by .grid()

**Comment by Sneezedip** [comment]
Fixed in Version 1.2.0
